# Generated by Django 2.2 on 2020-03-28 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
                ('sex', models.CharField(choices=[('f', '女'), ('m', '男')], help_text='Please enter user', max_length=1, verbose_name='性别')),
                ('head_image', models.ImageField(blank=True, help_text='Please upload your portrait', upload_to='head', verbose_name='头像')),
                ('telephone', models.CharField(error_messages={'unique': 'A telephone number with this already exists.'}, help_text='Please write your cell-phone number', max_length=11, unique=True, verbose_name='手机号')),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumer', to=settings.AUTH_USER_MODEL, verbose_name='消费者')),
            ],
            options={
                'verbose_name': '消费者',
                'verbose_name_plural': '消费者',
            },
            managers=[
                ('consumer_', django.db.models.manager.Manager()),
            ],
        ),
    ]
