# Generated by Django 2.2 on 2020-03-25 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shopper_app', '0001_initial'),
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(help_text='Please enter the name of the product', max_length=100, verbose_name='商品名称')),
                ('price', models.PositiveIntegerField(help_text='Please enter the price of the goods', verbose_name='价格')),
                ('details', mdeditor.fields.MDTextField(help_text='Please describe your product in detail', verbose_name='商品的详细描述')),
                ('intro', models.TextField(help_text='A briefly describe', verbose_name='商品的简要描述')),
                ('category', models.CharField(choices=[('衣服', '衣服'), ('裤子', '裤子'), ('鞋子', '鞋子'), ('电子设备', '电子设备'), ('化妆品', '化妆品'), ('食品', '食品')], help_text='Please select the type of goods', max_length=10, verbose_name='商品类别')),
                ('status', models.CharField(choices=[('Unshelve', '下架'), ('Onshelve', '上架')], help_text='Please select the sale status', max_length=10, verbose_name='上架状态')),
                ('shopper', models.ForeignKey(help_text='商品所属的商家', on_delete=django.db.models.deletion.CASCADE, related_name='commodity', to=settings.AUTH_USER_MODEL, verbose_name='商家')),
                ('store', models.ForeignKey(help_text='商品所在的店铺', on_delete=django.db.models.deletion.CASCADE, related_name='commodity', to='Shopper_app.Store', verbose_name='商铺')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
            },
            managers=[
                ('commodity_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_trolley',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='The quantity of this goods', verbose_name='quantity')),
                ('intro', models.TextField(help_text='A briefly describe', verbose_name='content')),
                ('price', models.PositiveIntegerField(help_text='Please enter the price of the goods', verbose_name='商品价格')),
                ('commodity_name', models.CharField(help_text='Please enter the name of the product', max_length=100, verbose_name='商品名')),
                ('store_name', models.CharField(help_text='the definition name of store', max_length=30, unique=True, verbose_name='店铺名')),
                ('store', models.BooleanField(default=True, help_text='商品上架还是下架，店铺存在还是不存在', verbose_name='商品上架状态')),
                ('user', models.OneToOneField(help_text='购物车归属的用户', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_trolley', to='User_app.Consumer', verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.PositiveIntegerField(help_text='Please enter the inventory of the goods', verbose_name='库存量')),
                ('purchase_number', models.PositiveIntegerField(help_text='Please fill in the quantity of purchase', verbose_name='进货数量')),
                ('purchase_time', models.DateTimeField(auto_now=True, verbose_name='进货时间')),
                ('commodity', models.ForeignKey(help_text='库存中的商品', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='Shop_app.Commodity', verbose_name='商品')),
                ('user', models.OneToOneField(help_text='您', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='商家')),
            ],
            options={
                'verbose_name': '库存表',
                'verbose_name_plural': '库存表',
            },
        ),
    ]
