# Generated by Django 2.2 on 2020-03-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_trolley',
            name='sex',
            field=models.CharField(blank=True, choices=[('m', '男'), ('f', '女')], help_text='性别', max_length=1, verbose_name='性别'),
        ),
    ]
