# Generated by Django 2.2 on 2020-03-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0002_shopping_trolley_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_trolley',
            name='sex',
        ),
    ]
