# Generated by Django 2.2 on 2020-03-27 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shop_app', '0001_initial'),
        ('Shopper_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generate_time', models.DateTimeField(auto_now_add=True, verbose_name='生成订单时间')),
                ('check_time', models.DateTimeField(auto_now=True, verbose_name='审核完毕订单时间')),
                ('check_status', models.CharField(choices=[('Unchecked', 'Unchecked'), ('Checked', 'Checked')], default='Unchecked', help_text='Please check the order of customers', max_length=20, verbose_name='审核状态')),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='Please check the quantity of the goods', verbose_name='商品数量')),
                ('belong_shopper', models.ForeignKey(help_text='该商品所对应的商家', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Shopper_app.Shoppers', verbose_name='商家')),
                ('commodity', models.OneToOneField(help_text='The goods corresponding to this order', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Shop_app.Commodity', verbose_name='商品')),
                ('shopping_trolley', models.ForeignKey(help_text='Shopping trolley', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Shop_app.Shopping_trolley', verbose_name='购物车')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'order',
                'ordering': ('-generate_time',),
            },
            managers=[
                ('order_', django.db.models.manager.Manager()),
            ],
        ),
    ]
