"""
自定义业务逻辑Code
"""

VERIFICATION_CODE_SUCCESS = 1
VERIFICATION_CODE_ERROR = 0
LOGIN_VERIFICATION_SUCCESS = 11
LOGIN_VERIFICATION_ERROR = -10
REGISTER_VERIFICATION_SUCCESS = 21
REGISTER_VERIFICATION_ERROR = -20
EMAIL_VERIFICATION_SUCCESS = 31
EMAIL_VERIFICATION_ERROR = -30
PHONE_VERIFICATION_SUCCESS = 41
PHONE_VERIFICATION_ERROR = -40
FIND_PASSWORD_VERIFICATION_SUCCESS = 51
FIND_PASSWORD_VERIFICATION_ERROR =-50
MODIFY_PASSWORD_VERIFICATION_SUCCESS = 61
MODIFY_PASSWORD_VERIFICATION_ERROR = -60
USER_EXISTS = 7



