# Generated by Django 2.2 on 2020-03-25 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Remark_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='shopper',
            field=models.ForeignKey(help_text='评论的商家', on_delete=django.db.models.deletion.CASCADE, related_name='remark', to=settings.AUTH_USER_MODEL, verbose_name='商家'),
        ),
    ]
