# Generated by Django 2.2 on 2020-03-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remark_app', '0002_auto_20200325_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='reward_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='remark_reply',
            name='reply_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='回复时间'),
        ),
    ]
