# Generated by Django 2.2 on 2020-03-27 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, error_messages={'unique': 'A Store with that store_name already exists.'}, help_text='Please personalize the definition name ', max_length=30, unique=True, verbose_name='店铺')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('province', models.CharField(blank=True, help_text='Please select province', max_length=10, verbose_name='省份')),
                ('city_choice', models.CharField(blank=True, help_text='Please select city', max_length=20, verbose_name='城市')),
                ('attention', models.PositiveIntegerField(default=0, help_text='Store attention', verbose_name='关注量')),
                ('shop_grade', models.DecimalField(decimal_places=1, default=0.0, help_text='Please write shop grade about this shop', max_digits=2, verbose_name='shop grade')),
                ('shopper', models.OneToOneField(help_text='Please write your name', on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL, verbose_name='商家')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
            },
            managers=[
                ('store_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Shoppers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, help_text='Please write your telephone', max_length=15, verbose_name='电话号码')),
                ('shop_credit', models.CharField(choices=[('1星', '1星'), ('2星', '2星'), ('3星', '3星'), ('4星', '4星'), ('5星', '5星'), ('2钻', '2钻'), ('3钻', '3钻'), ('4钻', '4钻'), ('5钻', '5钻')], default='1星', help_text='this display the rank of your credit on your shop', max_length=4, verbose_name='信誉')),
                ('shopper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopper', to=settings.AUTH_USER_MODEL, verbose_name='商铺管理员')),
            ],
            options={
                'verbose_name': '商家表',
                'verbose_name_plural': '商家表',
            },
            managers=[
                ('shoppers_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ips', models.CharField(help_text='ip地址', max_length=12, verbose_name='ip地址')),
                ('login_time', models.DateTimeField(auto_now_add=True, help_text='登录的时间', verbose_name='上线时间')),
                ('exit_time', models.DateTimeField(blank=True, help_text='退出网站的时间', verbose_name='下线时间')),
                ('shopper', models.ForeignKey(help_text='商家', on_delete=django.db.models.deletion.CASCADE, related_name='ip', to=settings.AUTH_USER_MODEL, verbose_name='商家')),
            ],
            managers=[
                ('ip_', django.db.models.manager.Manager()),
            ],
        ),
    ]
